version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ff-esports-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ffesports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ff-esports-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: ff-esports-api
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/ffesports?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: super_secret_esports_jwt_key_998877665544332211
      BOT_CALLBACK_SECRET: secure_bot_engine_signature_token
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  web-admin:
    build:
      context: .
      dockerfile: docker/Dockerfile.admin
    container_name: ff-esports-web
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://localhost:5000"
    ports:
      - "3000:3000"
    depends_on:
      - backend-api

  bot-observer:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: ff-esports-bot
    restart: always
    environment:
      API_URL: "http://backend-api:5000"
      BOT_CALLBACK_SECRET: secure_bot_engine_signature_token
      REDIS_HOST: redis
    depends_on:
      - backend-api
      - redis

volumes:
  postgres_data:
  redis_data:
