FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY apps/web-admin ./apps/web-admin

RUN npm install
RUN npm --prefix apps/web-admin run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/web-admin/public ./apps/web-admin/public
COPY --from=builder /app/apps/web-admin/.next/standalone ./
COPY --from=builder /app/apps/web-admin/.next/static ./apps/web-admin/.next/static

EXPOSE 3000
CMD ["node", "apps/web-admin/server.js"]
